---
baseurl: "/"
permalink: "/posts/:slug:output_ext"
title: Helen Suter Jewelry
snipcart_js: https://cdn.snipcart.com/themes/v3.0.8/default/snipcart.js
snipcart_css: https://cdn.snipcart.com/themes/v3.0.8/default/snipcart.css
snipcart_api_key: MzJlNDI2YWItODlmNC00M2EwLTk1NTYtNTExOWZlOTdlZGZmNjM2Njk2ODE3MjAxNDcwNjM3
logos:
  light:
    optimized: images/hs-jewelry-logo-light.svg
    fallback: images/hs-jewelry-logo-light.svg
  dark:
    optimized: images/hs-jewelry-logo-dark.svg
    fallback: images/hs-jewelry-logo-dark.svg
palette: default
palettes:
  default:
    sass:
      default: "#FFFFFF"
      light: "#F0F0F0"
      medium: "#6D6F6F"
      dark: "#3F3F3F"
      active: "#ffcb00"
      active_light: "#ffeb9d"
      active_medium: "#ffcf14"
      active_dark: "#9d7d00"
      dark_grey: "#273132"
      light_grey: "#6B797A"
      overlay_color1: rgba(217, 194, 8, 0.71)
      overlay_color2: rgba(244, 195, 2, 0)
      promo_background: "#de206182"
      bg_image_primary_optimized: "/images/DSC_9350_1.jpg"
      bg_image_primary_fallback: "/images/DSC_9350_1.jpg"
      bg_image_secondary_optimized: "/images/leaf-light-grey.svg"
      bg_image_secondary_fallback: "/images/leaf-light-grey.svg"
      bg_image_product_optimized: "/images/leaf.svg"
      bg_image_product_fallback: "/images/leaf.svg"
      bg_image_cart_optimized: "/images/cart-bg.webp"
      bg_image_cart_fallback: "/images/cart-bg.jpg"
sass:
  style: nested
  precision: 10
  indentWidth: 4
plugins:
- jekyll-menus
- jekyll-seo-tag
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
