---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: https://api.stackbit.com/project/5da09ea2967ea4001ae964bf/webhook/forestry
sections:
- type: document
  path: _config.yaml
  label: Theme Settings
- type: heading
  label: Pages
- type: document
  path: index.md
  label: Home
  templates:
  - index
- type: document
  path: faq.md
  label: FAQ
  templates:
  - faq
- type: document
  path: about.md
  label: About
  templates:
  - about
- type: heading
  label: Content
- type: directory
  path: category
  label: Categories
  create: all
  match: "**/*"
  templates:
  - categories
- type: directory
  path: material
  label: Material
  create: all
  match: "**/*"
  templates:
  - material
- type: document
  path: _data/promotion.json
  label: Promotion
  templates:
  - promotion
- type: document
  path: _data/testimonials.json
  label: Testimonials
  templates:
  - testimonials
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
