---
label: Product
hide_body: false
fields:
- type: text
  name: id
  label: ID
- type: text
  name: title
  label: Title
- type: text
  name: description
  label: Description
- type: text
  name: price
  label: Price
- type: field_group
  name: images
  label: Images
  fields:
  - type: field_group
    name: default
    label: Default
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
  - type: field_group
    name: featured
    label: Featured
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
- type: select
  name: category
  label: Category
  config:
    source:
      type: simple
    options:
    - necklaces
    - bracelets
    - earrings
- type: select
  name: material
  label: Material
  config:
    source:
      type: simple
    options:
    - gold
    - copper
    - sterling-silver
    - grey-patina
- type: boolean
  name: featured
  label: Featured
- type: select
  name: section
  label: Section
  config:
    source:
      type: simple
    options:
    - Store
    - About
    - Home
  default: Store
- type: text
  name: layout
  label: Layout
  hidden: true
  default: product
  config:
    required: true
pages:
- products/black-wood-necklace.md
- products/bracelet-1-1.md
- products/bracelet-1.md
- products/bracelet-11.md
- products/bracelet-12.md
- products/bracelet-13.md
- products/bracelet-14.md
- products/bracelet-15.md
- products/bracelet-16.md
- products/bracelet-17.md
- products/bracelet-18.md
- products/bracelet-19.md
- products/bracelet-2.md
- products/bracelet-20.md
- products/bracelet-21.md
- products/bracelet-22.md
- products/bracelet-23.md
- products/bracelet-24.md
- products/bracelet-3-1.md
- products/bracelet-3.md
- products/bracelet-5.md
- products/bracelet-6.md
- products/bracelet-7.md
- products/bracelet-8.md
- products/bracelet-9-1.md
- products/bracelet-9.md
- products/earring-000.md
- products/earring-001-1.md
- products/earring-001.md
- products/earring-002.md
- products/earring-003.md
- products/earring-004.md
- products/earring-005.md
- products/earring-006.md
- products/earring-007.md
- products/earring-008.md
- products/earring-009.md
- products/earring-010.md
- products/earring-011.md
- products/earring-012.md
- products/earring-013.md
- products/earring-014.md
- products/earring-015.md
- products/earring-016.md
- products/earring-017.md
- products/earring-018.md
- products/necklace-002.md
- products/necklace-003.md
- products/necklace-004.md
- products/necklace-005.md
- products/necklace-006.md
- products/necklace-1-1.md
- products/necklace-1.md
- products/necklace-2.md
- products/plant2.md
- products/plant3.md
- products/plant4.md
- products/plant6.md
- products/plant8.md
- products/plant9.md
- products/white-marble-necklace.md
- products/white-quartz-bracelet.md
