---
label: Product
hide_body: false
fields:
- type: text
  name: id
  label: ID
- type: text
  name: title
  label: Title
- type: text
  name: description
  label: Description
- type: text
  name: price
  label: Price
- type: field_group
  name: images
  label: Images
  fields:
  - type: field_group
    name: default
    label: Default
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
  - type: field_group
    name: featured
    label: Featured
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
- type: select
  name: category
  label: Category
  config:
    source:
      type: simple
    options:
    - necklaces
    - bracelets
    - earrings
- type: select
  name: material
  label: Material
  config:
    source:
      type: simple
    options:
    - gold
    - copper
    - sterling-silver
    - grey-patina
- type: boolean
  name: featured
  label: Featured
- type: select
  name: section
  label: Section
  config:
    source:
      type: simple
    options:
    - Store
    - About
    - Home
  default: Store
- type: text
  name: layout
  label: Layout
  hidden: true
  default: product
  config:
    required: true
- name: weight
  type: number
  label: Weight
  description: 'This weight in grams will be used to calculate shipping costs automatically. '
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: permalink
  type: text
  config:
    required: false
  label: Page URL
  description: 'The link for this page. Must begin with / and end with /. '
pages:
- products/amber-agate-necklace.md
- products/aqua-seaglass-bracelet.md
- products/clear-pink-czech-glass-bracelet.md
- products/dalmation-spots-necklace.md
- products/earthy-jasper-necklace.md
- products/grey-swirl-necklace.md
- products/large-baroque-pearl-bracelet.md
- products/marbled-facet-bracelet.md
- products/marbled-pink-czech-glass-bracelet.md
- products/medium-baroque-pearl-bracelet.md
- products/peacock-bracelet-black.md
- products/peacock-bracelet-blue.md
- products/peacock-bracelet-turqoise.md
- products/pink-quartz-bracelet.md
- products/seaglass-multi-bracelet-1.md
- products/seaglass-multi-bracelet.md
